### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by zzfancitizen** [MatthewGeekTalk/ML-Git#1]
__find_plate_number_region中的trect队列时干嘛用的？
还有检查角度这段逻辑。
` if (rect[2] <= -5 or rect[2] >= 5): 
 safe_region.append(safe_box)
else:
region.append(box)`
不明白这段代码的用途。
这会导致region和safe region不匹配的问题。

还有__calc_safe_rect的时候
`if w < 0 or h < 0 or w < h:`
为什么要判别宽与长的大小？

**Comment by MatthewGeekTalk** [comment]
1: 判断角度是为了后面做旋转用的. 现在代码已经改了. 不用区分region和safe region了 都拿safe region来做. 把safe region和angle配对存起来. 后面可以直接用来做旋转.

2: 算出safe region后, h,w和box点的顺序就都确定下来了. 可以用来排除那种h>w的矩形
